### ISSUE TITLE
The PasswordRequiresUniqueChars method of pl-PL language uses the wrong code

### ISSUE THREAD

**Issue by VAllens** [piotrtrojan/PiotrTrojan.AspNetCore.IdentityErrorLocalization#3]
Hi, the `PasswordRequiresUniqueChars` method of `pl-PL` language uses the wrong code.

`source/PiotrTrojan.AspNetCore.IdentityErrorLocalization.pl-PL/PolishIdentityErrorDescriber.cs` :

```csharp
public override IdentityError PasswordRequiresUniqueChars(int uniqueChars) => new() { Code = nameof(PasswordRequiresNonAlphanumeric), Description = "Hasło musi posiadać przynajmniej jeden znak specjalny." };
```

**Comment by VAllens** [comment]
Please see here, I submitted [a PR 4](https://github.com/piotrtrojan/PiotrTrojan.AspNetCore.IdentityErrorLocalization/pull/4).

**Comment by milons** [comment]
PR Merged
