### ISSUE TITLE
PT-BR version

### ISSUE THREAD

**Issue by Walter-Alipio** [piotrtrojan/PiotrTrojan.AspNetCore.IdentityErrorLocalization#5]
I notice that the project have PT version but not a PT-BR. It could be made with a few adjusts in `PortugueseIdentityErrorDescriber.cs` like this:
PT - `... Description = $"O utilizador '{userName}' já está sendo utilizado." }`
PT-BR - `... Description = $"O usuário '{userName}' já está sendo utilizado." }`

**Comment by milons** [comment]
@Walter-Alipio feel free to create PR with translations or write them down. I do not speak pt-br.
